#!/usr/bin/env python3
"""Generate tmp/trap_names.lua -- the A-trap word -> name map used by mac_traps.lua.

⚠ The names are NOT vendored into this repo.  The source table is cxmon's
`mon_atraps.h` (Basilisk II / SheepShaver), which is GPL; the names themselves
are Apple's published API names from Inside Macintosh, but the file is not ours
to redistribute, so it is fetched on demand into tmp/ (local only, like every
other piece of non-distributable material here).

    python3 tools/gen_trap_names.py          # fetch + generate
    python3 tools/gen_trap_names.py FILE     # from an already-downloaded copy

⭐ Key facts about the encoding, so a miss is a real miss and not a lookup bug:
  * bit 11 ($0800) set  -> TOOLBOX trap.  Trap number is the low TEN bits, and
    the table's key is $A800 + number.  Bit 10 ($0400) is the auto-pop flag and
    must be masked out before the lookup.
  * bit 11 clear        -> OS trap.  Trap number is the low EIGHT bits and the
    table's key is $A000 + number.  Bits 10/9/8 are flags (trash-A0, sys-heap,
    clear-memory) and must be masked out too.
  ⚠ $AAxx traps only exist when the trap table is the 1024-entry kind; on a
    512-entry table $AA6E aliases $A86E (InitGraf).  A Mac II with System 6 has
    the big table, which is why the $AAxx rows below are real traps.
"""
import re, sys, os, urllib.request

URL = "https://raw.githubusercontent.com/cebix/macemu/master/cxmon/src/mon_atraps.h"
OUT = "tmp/trap_names.lua"

src = open(sys.argv[1], "rb").read() if len(sys.argv) > 1 else urllib.request.urlopen(URL, timeout=30).read()
rows = re.findall(rb'\{\s*"([A-Za-z0-9_]+)"\s*,\s*0x([Aa][0-9A-Fa-f]{3})\s*\}', src)
if len(rows) < 500:
    sys.exit("only %d traps parsed -- the source format changed, do NOT ship a partial table" % len(rows))

os.makedirs("tmp", exist_ok=True)
with open(OUT, "w") as f:
    f.write("-- GENERATED by tools/gen_trap_names.py -- do not edit, do not commit.\n")
    f.write("-- Source: %s\n-- %d traps.\n" % (URL, len(rows)))
    f.write("return {\n")
    for name, word in rows:
        f.write('\t[0x%s] = "%s",\n' % (word.decode().upper(), name.decode()))
    f.write("}\n")
print("wrote %s, %d traps" % (OUT, len(rows)))
